apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  # storageClassName: manual # locally
  storageClassName: standard # gcloud
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi